### ISSUE TITLE
Can't build due to module.modulemap location

### ISSUE THREAD

**Issue by placrosse** [SUIRON/CLMDB#1]
$ swift -version
Swift version 3.1 (swift-3.1-RELEASE)
Target: x86_64-unknown-linux-gnu
$ swift package clean
$ swift build
Fetching https://github.com/SUIRON/SwiftLMDB.git
Fetching https://github.com/SUIRON/CLMDB.git
Cloning https://github.com/SUIRON/SwiftLMDB.git
Resolving https://github.com/SUIRON/SwiftLMDB.git at 0.0.5
Cloning https://github.com/SUIRON/CLMDB.git
Resolving https://github.com/SUIRON/CLMDB.git at 0.0.1
error: the package has an unsupported layout, modulemap 
(***/.build/checkouts/CLMDB.git-2691187057038354126/Sources/module.modulemap) is not allowed to be mixed with sources
fix: move the modulemap inside include directory

**Comment by eriktier** [comment]
Thanks! Looking into it.

**Comment by eriktier** [comment]
Fixed it (0.0.3), however, there now seems to be a linker error in SwiftLMDB. So more fixing is needed.
